version: '3.8'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: yourdbname
      MYSQL_USER: yourdbuser
      MYSQL_PASSWORD: yourdbpassword
      MYSQL_ROOT_PASSWORD: yourrootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  web:
    build: .
    volumes:
      - .:/cookbook
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=yourdbname
      - DB_USER=yourdbuser
      - DB_PASSWORD=yourdbpassword
      - DB_HOST=db
      - DB_PORT=3306

volumes:
  db_data:
