# Generated by Django 3.2.7 on 2024-09-03 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='sub_recipe',
        ),
    ]
