# Generated by Django 3.2.7 on 2024-09-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_recipe_sub_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
