# Generated by Django 3.2.15 on 2023-02-16 14:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('ingredients', models.CharField(blank=True, max_length=5000, null=True)),
                ('instructions', models.CharField(blank=True, max_length=50000, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('cooktime', models.CharField(max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sub_recipe', models.ManyToManyField(blank=True, related_name='recipes_contain', to='cookbook.Recipe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
