# Generated by Django 3.2.7 on 2024-08-28 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='sub_recipe',
        ),
    ]
